export const TEST = 'test';
export const GET_ERRORS = 'GET_ERRORS';
export const DELETE_ERRORS = 'DELETE_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_PERSONS = 'GET_PERSONS';
export const CLEAR_PERSONS = 'CLEAR_PERSONS';
export const CREATE_PERSON = 'CREATE_PERSON';
export const GET_USERS = 'GET_USERS';
export const CLEAR_USERS = 'CLEAR_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';

export const GET_TASK_FILTER_BY_DATE = 'GET_TASK_FILTER_BY_DATE';
export const GET_ACTIVE_EMPLOYEES = 'GET_ACTIVE_EMPLOYEES';
export const GET_TECHNICIANS = 'GET_TECHNICIANS';
export const GET_COVERAGE_BY_IDREGWS = 'GET_COVERAGE_BY_IDREGWS';
export const GET_PARTS_BY_IDREGWS = 'GET_PARTS_BY_IDREGWS';
export const GET_TASKS_EQP = 'GET_TASKS_EQP';

export const GET_CATALOGO_EQP = 'GET_CATALOGO_EQP';
export const GET_EQUIPOS_ACTIVOS = 'GET_EQUIPOS_ACTIVOS';
export const GET_TAREAS_BY_EQP = 'GET_TAREAS_BY_EQP';
export const GET_REPUESTOS_BY_EQP = 'GET_REPUESTOS_BY_EQP';
export const GET_COBERTURA = 'GET_COBERTURA';

export const GET_INGRESADO_PENDIENTE = 'GET_INGRESADO_PENDIENTE';

export const GET_DESEMPENO_TECNICOS = 'GET_DESEMPENO_TECNICOS';



