export const TEST = 'test';
export const GET_ERRORS = 'GET_ERRORS';
export const DELETE_ERRORS = 'DELETE_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_PERSONS = 'GET_PERSONS';
export const CLEAR_PERSONS = 'CLEAR_PERSONS';
export const CREATE_PERSON = 'CREATE_PERSON';
export const GET_USERS = 'GET_USERS';
export const CLEAR_USERS = 'CLEAR_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const CREATE_NOTIFICACION_PROCESS = 'CREATE_NOTIFICACION_PROCESS';

export const OBT_ASIGNACIONES_POR_FECHA = 'OBT_ASIGNACIONES_POR_FECHA';
export const OBT_EMPLEADOS_ACTIVOS = 'OBT_EMPLEADOS_ACTIVOS';
export const OBT_TECNICOS_ACTIVOS = 'OBT_TECNICOS_ACTIVOS';
export const OBT_COBERTURA_POR_IDREGWS = 'OBT_COBERTURA_POR_IDREGWS';
export const OBT_PARTES_POR_IDREGWS = 'OBT_PARTES_POR_IDREGWS';
export const OBT_TAREAS_DEL_EQP = 'OBT_TAREAS_DEL_EQP';

export const OBT_CATALOGO_EQP = 'OBT_CATALOGO_EQP';
export const OBT_EQUIPOS_ACTIVOS = 'OBT_EQUIPOS_ACTIVOS';
export const OBT_TAREAS_POR_EQP = 'OBT_TAREAS_POR_EQP';
export const OBT_REPUESTOS_POR_EQP = 'OBT_REPUESTOS_POR_EQP';
export const OBT_COBERTURA_EQP = 'OBT_COBERTURA_EQP';

export const OBT_INGRESADOS_PENDIENTES = 'OBT_INGRESADOS_PENDIENTES';

export const OBT_DATOS_DESEMPENO_TECNICOS = 'OBT_DATOS_DESEMPENO_TECNICOS';
export const LIMPIAR_DATOS_REPORTE = 'LIMPIAR_DATOS_REPORTE';
export const OBT_DATOS_DISTRIBUCION_TIEMPO = 'OBT_DATOS_DISTRIBUCION_TIEMPO';


